### ISSUE TITLE
any idea about transforming bytecode to standard python ast?

### ISSUE THREAD

**Issue by thautwarm** [vtheno/vcheck#1]
like, given a code object,  produce an `Module` AST.

**Comment by vtheno** [comment]
emmm, good question , maybe can set up a two-way conversion protocol for a code object to an AST.
like:
`
b if a else c    ;; (if a b c) ;; if expr1 expr2 expr3
` always compiler to 
```
LOAD_NAME a  ; expr1 in here
POP_JUMP_IF_FALSE (calc label1) ; spec
LOAD_NAME b  ; expr2 in here
RETURN_VALUE; spec
(label1) ; spec
LOAD_NAME c ; expr3 in here 
RETURN_VALUE ; spec
```
and , this < if ... else ... > block always equal the < ... if ... else ...>,

in fact , if code objects follow a protocol specification , then need a compile function convert ast to codeobj then it can backto ast, if only if compile function follow the spec

**Comment by thautwarm** [comment]
check out https://github.com/rocky/python-uncompyle6 , a rabbit told me this.

**Comment by thautwarm** [comment]
Also, check your email.  I've send an invitation to you for the items about joining Xython.
